[unix_http_server]
file=/var/run/supervisor.sock

[supervisord]
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
loglevel=info
pidfile=/var/run/supervisord.pid
nodaemon=false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:guardian]
command=python -u bot.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/guardian.err.log
stdout_logfile=/var/log/supervisor/guardian.out.log
environment=PYTHONUNBUFFERED="1"

[program:antygravity]
command=python -u antygravity_bot.py
directory=/app
autostart=true
autorestart=true
stopwaitsecs=10
stderr_logfile=/var/log/supervisor/antygravity.err.log
stdout_logfile=/var/log/supervisor/antygravity.out.log
environment=PYTHONUNBUFFERED="1"
